server:
  port: 9002
eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:9000/eureka
  instance:
    instance-id: ${spring.application.name}:${instanceId:${random.value}}
    preferIpAddress: true
spring:
  application:
    name: gatewayService
  cloud:
    gateway:
      mvc:
        routes[0]:
          id: customerService
          predicates[0]: Path=/customerservice/api/v1/customers/**
          uri: lb://CUSTOMERSERVICE
        routes[1]:
          id: discoveryServer
          predicates[0]: Path=/eureka/web
          filters[0]: SetPath=/
          uri: http://localhost:9000
        routes[2]:
          id: accountService
          predicates[0]: Path=/accountservice/api/v1/accounts/**
          uri: lb://ACCOUNTSERVICE
        routes[3]:
          id: searchService
          predicates[0]: Path=/searchservice/api/v1/filters/**
          uri: lb://SEARCHSERVICE
        routes[4]:
          id: catalogService
          predicates[0]: Path=/catalogservice/api/v1/catalogs/**
          uri: lb://CATALOGSERVICE

